hare test: fails when a module dependency is missing
Sometime "hare test" silently ignore modules that does not build. As
a false negative, this is a massive footgun when refactorizing a code
base. This only happen sometime, with specific build errors, when a
module dependency is not found.

In the following example, the module bar:: is failing to build, because
the module "invalid::hare::module" does not exists. But "hare test"
just ignore it:

	./
	├── bar/
	│   ├── bar.ha:
	│   │ use invalid::hare::module;
	│   │
	│   ├── test+test.ha:
	│   │ @test fn test() void = {
	│   │ 	assert(false);
	│   │ };
	│   └
	├── foo/
	│   ├── foo.txt:
	│   │ some file
	│   └
	└── toot/
	    ├── toot.ha:
	    │
	    │ @test fn test() void = {
	    │ 	assert(true);
	    │ };
	    └

	$ hare test
	Running 1/1 tests:

	toot::test...PASS in 0.000002800s

	1 passed; 0 failed; 1 completed in 0.000002800s

The problem comes from the hare::module gathering. We use a not_found
error that is returned both when a {path::path,ast::ident} does not
exists in the filesystem, and when a dependency can't be found.

To solve the issue, we now distinguish both, and convert a not_found
to a dep_missing when gathering a module dependencies.

I just have a problem with how it is reported with this patch:

	$ hare test
	Error: Dependency missing: invalid::hare::module

I would prefer to prefix the failing to build module identifier, but I'm
not sure on the best way to this with the current hare::module errors
context.

Signed-off-by: Willow Barraco <contact@willowbarraco.fr>